/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage
 * @generated
 */
public interface AiDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AiDslFactory eINSTANCE = de.mindscan.ai.aidsl.aiDsl.impl.AiDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Workflow Functions Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow Functions Definition</em>'.
   * @generated
   */
  WorkflowFunctionsDefinition createWorkflowFunctionsDefinition();

  /**
   * Returns a new object of class '<em>SAI Member</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Member</em>'.
   * @generated
   */
  SAIMember createSAIMember();

  /**
   * Returns a new object of class '<em>SAI Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Field</em>'.
   * @generated
   */
  SAIField createSAIField();

  /**
   * Returns a new object of class '<em>SAI Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Method</em>'.
   * @generated
   */
  SAIMethod createSAIMethod();

  /**
   * Returns a new object of class '<em>SAI Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Parameter</em>'.
   * @generated
   */
  SAIParameter createSAIParameter();

  /**
   * Returns a new object of class '<em>SAI Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Block</em>'.
   * @generated
   */
  SAIBlock createSAIBlock();

  /**
   * Returns a new object of class '<em>SAI Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Statement</em>'.
   * @generated
   */
  SAIStatement createSAIStatement();

  /**
   * Returns a new object of class '<em>SAI Variable Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Variable Declaration</em>'.
   * @generated
   */
  SAIVariableDeclaration createSAIVariableDeclaration();

  /**
   * Returns a new object of class '<em>SAI Return</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Return</em>'.
   * @generated
   */
  SAIReturn createSAIReturn();

  /**
   * Returns a new object of class '<em>SAI If Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI If Statement</em>'.
   * @generated
   */
  SAIIfStatement createSAIIfStatement();

  /**
   * Returns a new object of class '<em>SAI If Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI If Block</em>'.
   * @generated
   */
  SAIIfBlock createSAIIfBlock();

  /**
   * Returns a new object of class '<em>SAI Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Expression</em>'.
   * @generated
   */
  SAIExpression createSAIExpression();

  /**
   * Returns a new object of class '<em>Package Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Package Declaration</em>'.
   * @generated
   */
  PackageDeclaration createPackageDeclaration();

  /**
   * Returns a new object of class '<em>Import Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import Declaration</em>'.
   * @generated
   */
  ImportDeclaration createImportDeclaration();

  /**
   * Returns a new object of class '<em>Workflow Input Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow Input Definition</em>'.
   * @generated
   */
  WorkflowInputDefinition createWorkflowInputDefinition();

  /**
   * Returns a new object of class '<em>Workflow UI Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow UI Element</em>'.
   * @generated
   */
  WorkflowUIElement createWorkflowUIElement();

  /**
   * Returns a new object of class '<em>Workflow UI Element Map</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow UI Element Map</em>'.
   * @generated
   */
  WorkflowUIElementMap createWorkflowUIElementMap();

  /**
   * Returns a new object of class '<em>Workflow Data Dictionary Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow Data Dictionary Definition</em>'.
   * @generated
   */
  WorkflowDataDictionaryDefinition createWorkflowDataDictionaryDefinition();

  /**
   * Returns a new object of class '<em>Datadictionary Key Value Pair</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Datadictionary Key Value Pair</em>'.
   * @generated
   */
  DatadictionaryKeyValuePair createDatadictionaryKeyValuePair();

  /**
   * Returns a new object of class '<em>Data Dictionary Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Dictionary Value</em>'.
   * @generated
   */
  DataDictionaryValue createDataDictionaryValue();

  /**
   * Returns a new object of class '<em>Data Dictionary Array Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Dictionary Array Value</em>'.
   * @generated
   */
  DataDictionaryArrayValue createDataDictionaryArrayValue();

  /**
   * Returns a new object of class '<em>Data Dictionary Map Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Dictionary Map Value</em>'.
   * @generated
   */
  DataDictionaryMapValue createDataDictionaryMapValue();

  /**
   * Returns a new object of class '<em>Data Dictionary Boolean Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Dictionary Boolean Value</em>'.
   * @generated
   */
  DataDictionaryBooleanValue createDataDictionaryBooleanValue();

  /**
   * Returns a new object of class '<em>Data Dictionary String Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Dictionary String Value</em>'.
   * @generated
   */
  DataDictionaryStringValue createDataDictionaryStringValue();

  /**
   * Returns a new object of class '<em>Data Dictionary Null Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Dictionary Null Value</em>'.
   * @generated
   */
  DataDictionaryNullValue createDataDictionaryNullValue();

  /**
   * Returns a new object of class '<em>VM Node Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Node Definition</em>'.
   * @generated
   */
  VMNodeDefinition createVMNodeDefinition();

  /**
   * Returns a new object of class '<em>VM Node Eleemnts</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Node Eleemnts</em>'.
   * @generated
   */
  VMNodeEleemnts createVMNodeEleemnts();

  /**
   * Returns a new object of class '<em>VM Node Op Code Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Node Op Code Element</em>'.
   * @generated
   */
  VMNodeOpCodeElement createVMNodeOpCodeElement();

  /**
   * Returns a new object of class '<em>VM Node Out Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Node Out Elements</em>'.
   * @generated
   */
  VMNodeOutElements createVMNodeOutElements();

  /**
   * Returns a new object of class '<em>VM Node In Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Node In Elements</em>'.
   * @generated
   */
  VMNodeInElements createVMNodeInElements();

  /**
   * Returns a new object of class '<em>VM Node Field Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Node Field Elements</em>'.
   * @generated
   */
  VMNodeFieldElements createVMNodeFieldElements();

  /**
   * Returns a new object of class '<em>VM Node Out Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Node Out Element</em>'.
   * @generated
   */
  VMNodeOutElement createVMNodeOutElement();

  /**
   * Returns a new object of class '<em>VM Node In Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Node In Element</em>'.
   * @generated
   */
  VMNodeInElement createVMNodeInElement();

  /**
   * Returns a new object of class '<em>VM Field Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Field Element</em>'.
   * @generated
   */
  VMFieldElement createVMFieldElement();

  /**
   * Returns a new object of class '<em>VM Override Field Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VM Override Field Element</em>'.
   * @generated
   */
  VMOverrideFieldElement createVMOverrideFieldElement();

  /**
   * Returns a new object of class '<em>Llm Task Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llm Task Definition</em>'.
   * @generated
   */
  LlmTaskDefinition createLlmTaskDefinition();

  /**
   * Returns a new object of class '<em>Annotation Interface Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation Interface Reference</em>'.
   * @generated
   */
  AnnotationInterfaceReference createAnnotationInterfaceReference();

  /**
   * Returns a new object of class '<em>Llm Variable Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Llm Variable Assignment</em>'.
   * @generated
   */
  LlmVariableAssignment createLlmVariableAssignment();

  /**
   * Returns a new object of class '<em>Workflow Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow Definition</em>'.
   * @generated
   */
  WorkflowDefinition createWorkflowDefinition();

  /**
   * Returns a new object of class '<em>Workflow If Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow If Statement</em>'.
   * @generated
   */
  WorkflowIfStatement createWorkflowIfStatement();

  /**
   * Returns a new object of class '<em>Workflow Definition Apply LLM Task Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow Definition Apply LLM Task Statement</em>'.
   * @generated
   */
  WorkflowDefinitionApplyLLMTaskStatement createWorkflowDefinitionApplyLLMTaskStatement();

  /**
   * Returns a new object of class '<em>Workflow Definition Apply LLM Node Result Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow Definition Apply LLM Node Result Assignment</em>'.
   * @generated
   */
  WorkflowDefinitionApplyLLMNodeResultAssignment createWorkflowDefinitionApplyLLMNodeResultAssignment();

  /**
   * Returns a new object of class '<em>ELEMENTTYPE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ELEMENTTYPE</em>'.
   * @generated
   */
  ELEMENTTYPE createELEMENTTYPE();

  /**
   * Returns a new object of class '<em>BASICTYPE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BASICTYPE</em>'.
   * @generated
   */
  BASICTYPE createBASICTYPE();

  /**
   * Returns a new object of class '<em>SAI Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Assignment</em>'.
   * @generated
   */
  SAIAssignment createSAIAssignment();

  /**
   * Returns a new object of class '<em>SAI Member Selection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Member Selection</em>'.
   * @generated
   */
  SAIMemberSelection createSAIMemberSelection();

  /**
   * Returns a new object of class '<em>SAI String Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI String Constant</em>'.
   * @generated
   */
  SAIStringConstant createSAIStringConstant();

  /**
   * Returns a new object of class '<em>SAI Int Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Int Constant</em>'.
   * @generated
   */
  SAIIntConstant createSAIIntConstant();

  /**
   * Returns a new object of class '<em>SAI Bool Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Bool Constant</em>'.
   * @generated
   */
  SAIBoolConstant createSAIBoolConstant();

  /**
   * Returns a new object of class '<em>SAI Null</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SAI Null</em>'.
   * @generated
   */
  SAINull createSAINull();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AiDslPackage getAiDslPackage();

} //AiDslFactory
