/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SAI Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getSAIExpression()
 * @model
 * @generated
 */
public interface SAIExpression extends SAIStatement
{
} // SAIExpression
