/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SAI Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.SAIMethod#getParams <em>Params</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.SAIMethod#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getSAIMethod()
 * @model
 * @generated
 */
public interface SAIMethod extends SAIMember
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link de.mindscan.ai.aidsl.aiDsl.SAIParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getSAIMethod_Params()
   * @model containment="true"
   * @generated
   */
  EList<SAIParameter> getParams();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(SAIBlock)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getSAIMethod_Body()
   * @model containment="true"
   * @generated
   */
  SAIBlock getBody();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.SAIMethod#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(SAIBlock value);

} // SAIMethod
