/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SAI Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getSAIStatement()
 * @model
 * @generated
 */
public interface SAIStatement extends EObject
{
} // SAIStatement
