/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SAI Workflow Run Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.SAIWorkflowRunStatement#getTask <em>Task</em>}</li>
 * </ul>
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getSAIWorkflowRunStatement()
 * @model
 * @generated
 */
public interface SAIWorkflowRunStatement extends SAIStatement
{
  /**
   * Returns the value of the '<em><b>Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task</em>' reference.
   * @see #setTask(LlmTaskDefinition)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getSAIWorkflowRunStatement_Task()
   * @model
   * @generated
   */
  LlmTaskDefinition getTask();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.SAIWorkflowRunStatement#getTask <em>Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Task</em>' reference.
   * @see #getTask()
   * @generated
   */
  void setTask(LlmTaskDefinition value);

} // SAIWorkflowRunStatement
