/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VM Node Op Code Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.VMNodeOpCodeElement#getOpcode <em>Opcode</em>}</li>
 * </ul>
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getVMNodeOpCodeElement()
 * @model
 * @generated
 */
public interface VMNodeOpCodeElement extends VMNodeEleemnts
{
  /**
   * Returns the value of the '<em><b>Opcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opcode</em>' attribute.
   * @see #setOpcode(String)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getVMNodeOpCodeElement_Opcode()
   * @model
   * @generated
   */
  String getOpcode();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.VMNodeOpCodeElement#getOpcode <em>Opcode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opcode</em>' attribute.
   * @see #getOpcode()
   * @generated
   */
  void setOpcode(String value);

} // VMNodeOpCodeElement
