/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VM Node Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.VMNodeDefinition#getNodetype <em>Nodetype</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.VMNodeDefinition#getName <em>Name</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.VMNodeDefinition#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getVMNodeDefinition()
 * @model
 * @generated
 */
public interface VMNodeDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Nodetype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodetype</em>' attribute.
   * @see #setNodetype(String)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getVMNodeDefinition_Nodetype()
   * @model
   * @generated
   */
  String getNodetype();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.VMNodeDefinition#getNodetype <em>Nodetype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nodetype</em>' attribute.
   * @see #getNodetype()
   * @generated
   */
  void setNodetype(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getVMNodeDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.VMNodeDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link de.mindscan.ai.aidsl.aiDsl.VMNodeEleemnts}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getVMNodeDefinition_Elements()
   * @model containment="true"
   * @generated
   */
  EList<VMNodeEleemnts> getElements();

} // VMNodeDefinition
