/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow UI Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.WorkflowUIDefinition#getName <em>Name</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.WorkflowUIDefinition#getUiElements <em>Ui Elements</em>}</li>
 * </ul>
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowUIDefinition()
 * @model
 * @generated
 */
public interface WorkflowUIDefinition extends WorkflowInputDefinition
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowUIDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.WorkflowUIDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ui Elements</b></em>' containment reference list.
   * The list contents are of type {@link de.mindscan.ai.aidsl.aiDsl.WorkflowUIElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ui Elements</em>' containment reference list.
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowUIDefinition_UiElements()
   * @model containment="true"
   * @generated
   */
  EList<WorkflowUIElement> getUiElements();

} // WorkflowUIDefinition
