/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow Data Dictionary Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.WorkflowDataDictionaryElement#getName <em>Name</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.WorkflowDataDictionaryElement#getExtends <em>Extends</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.WorkflowDataDictionaryElement#getKeyValuePairs <em>Key Value Pairs</em>}</li>
 * </ul>
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowDataDictionaryElement()
 * @model
 * @generated
 */
public interface WorkflowDataDictionaryElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowDataDictionaryElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.WorkflowDataDictionaryElement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Extends</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extends</em>' reference.
   * @see #setExtends(WorkflowDataDictionaryElement)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowDataDictionaryElement_Extends()
   * @model
   * @generated
   */
  WorkflowDataDictionaryElement getExtends();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.WorkflowDataDictionaryElement#getExtends <em>Extends</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extends</em>' reference.
   * @see #getExtends()
   * @generated
   */
  void setExtends(WorkflowDataDictionaryElement value);

  /**
   * Returns the value of the '<em><b>Key Value Pairs</b></em>' containment reference list.
   * The list contents are of type {@link de.mindscan.ai.aidsl.aiDsl.DatadictionaryKeyValuePair}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key Value Pairs</em>' containment reference list.
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowDataDictionaryElement_KeyValuePairs()
   * @model containment="true"
   * @generated
   */
  EList<DatadictionaryKeyValuePair> getKeyValuePairs();

} // WorkflowDataDictionaryElement
