/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow Definition Apply LLM Task Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.WorkflowDefinitionApplyLLMTaskStatement#getLlmtask <em>Llmtask</em>}</li>
 * </ul>
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowDefinitionApplyLLMTaskStatement()
 * @model
 * @generated
 */
public interface WorkflowDefinitionApplyLLMTaskStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Llmtask</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Llmtask</em>' reference.
   * @see #setLlmtask(LlmTaskDefinition)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowDefinitionApplyLLMTaskStatement_Llmtask()
   * @model
   * @generated
   */
  LlmTaskDefinition getLlmtask();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.WorkflowDefinitionApplyLLMTaskStatement#getLlmtask <em>Llmtask</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Llmtask</em>' reference.
   * @see #getLlmtask()
   * @generated
   */
  void setLlmtask(LlmTaskDefinition value);

} // WorkflowDefinitionApplyLLMTaskStatement
