/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow Functions Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.WorkflowFunctionsDefinition#getName <em>Name</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.WorkflowFunctionsDefinition#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowFunctionsDefinition()
 * @model
 * @generated
 */
public interface WorkflowFunctionsDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowFunctionsDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.mindscan.ai.aidsl.aiDsl.WorkflowFunctionsDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link de.mindscan.ai.aidsl.aiDsl.SAIMember}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see de.mindscan.ai.aidsl.aiDsl.AiDslPackage#getWorkflowFunctionsDefinition_Members()
   * @model containment="true"
   * @generated
   */
  EList<SAIMember> getMembers();

} // WorkflowFunctionsDefinition
