/*
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAiDslScopeProvider extends DelegatingScopeProvider {
}
