/*
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AiDslStandaloneSetup extends AiDslStandaloneSetupGenerated {

	public static void doSetup() {
		new AiDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
