/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl.impl;

import de.mindscan.ai.aidsl.aiDsl.AiDslPackage;
import de.mindscan.ai.aidsl.aiDsl.DataDictionaryNullValue;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Dictionary Null Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DataDictionaryNullValueImpl extends DataDictionaryValueImpl implements DataDictionaryNullValue
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataDictionaryNullValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AiDslPackage.Literals.DATA_DICTIONARY_NULL_VALUE;
  }

} //DataDictionaryNullValueImpl
