/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl.impl;

import de.mindscan.ai.aidsl.aiDsl.AiDslPackage;
import de.mindscan.ai.aidsl.aiDsl.DataDictionaryValue;
import de.mindscan.ai.aidsl.aiDsl.ELEMENTTYPE;
import de.mindscan.ai.aidsl.aiDsl.VMFieldElement;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>VM Field Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.impl.VMFieldElementImpl#getPolicy <em>Policy</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.impl.VMFieldElementImpl#getType <em>Type</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.impl.VMFieldElementImpl#getName <em>Name</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.impl.VMFieldElementImpl#getDefaultvalue <em>Defaultvalue</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VMFieldElementImpl extends MinimalEObjectImpl.Container implements VMFieldElement
{
  /**
   * The default value of the '{@link #getPolicy() <em>Policy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPolicy()
   * @generated
   * @ordered
   */
  protected static final String POLICY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPolicy() <em>Policy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPolicy()
   * @generated
   * @ordered
   */
  protected String policy = POLICY_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected ELEMENTTYPE type;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDefaultvalue() <em>Defaultvalue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultvalue()
   * @generated
   * @ordered
   */
  protected DataDictionaryValue defaultvalue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VMFieldElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AiDslPackage.Literals.VM_FIELD_ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPolicy()
  {
    return policy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPolicy(String newPolicy)
  {
    String oldPolicy = policy;
    policy = newPolicy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_FIELD_ELEMENT__POLICY, oldPolicy, policy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ELEMENTTYPE getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(ELEMENTTYPE newType, NotificationChain msgs)
  {
    ELEMENTTYPE oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_FIELD_ELEMENT__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(ELEMENTTYPE newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AiDslPackage.VM_FIELD_ELEMENT__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AiDslPackage.VM_FIELD_ELEMENT__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_FIELD_ELEMENT__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_FIELD_ELEMENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataDictionaryValue getDefaultvalue()
  {
    return defaultvalue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDefaultvalue(DataDictionaryValue newDefaultvalue, NotificationChain msgs)
  {
    DataDictionaryValue oldDefaultvalue = defaultvalue;
    defaultvalue = newDefaultvalue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE, oldDefaultvalue, newDefaultvalue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDefaultvalue(DataDictionaryValue newDefaultvalue)
  {
    if (newDefaultvalue != defaultvalue)
    {
      NotificationChain msgs = null;
      if (defaultvalue != null)
        msgs = ((InternalEObject)defaultvalue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE, null, msgs);
      if (newDefaultvalue != null)
        msgs = ((InternalEObject)newDefaultvalue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE, null, msgs);
      msgs = basicSetDefaultvalue(newDefaultvalue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE, newDefaultvalue, newDefaultvalue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_FIELD_ELEMENT__TYPE:
        return basicSetType(null, msgs);
      case AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE:
        return basicSetDefaultvalue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_FIELD_ELEMENT__POLICY:
        return getPolicy();
      case AiDslPackage.VM_FIELD_ELEMENT__TYPE:
        return getType();
      case AiDslPackage.VM_FIELD_ELEMENT__NAME:
        return getName();
      case AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE:
        return getDefaultvalue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_FIELD_ELEMENT__POLICY:
        setPolicy((String)newValue);
        return;
      case AiDslPackage.VM_FIELD_ELEMENT__TYPE:
        setType((ELEMENTTYPE)newValue);
        return;
      case AiDslPackage.VM_FIELD_ELEMENT__NAME:
        setName((String)newValue);
        return;
      case AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE:
        setDefaultvalue((DataDictionaryValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_FIELD_ELEMENT__POLICY:
        setPolicy(POLICY_EDEFAULT);
        return;
      case AiDslPackage.VM_FIELD_ELEMENT__TYPE:
        setType((ELEMENTTYPE)null);
        return;
      case AiDslPackage.VM_FIELD_ELEMENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE:
        setDefaultvalue((DataDictionaryValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_FIELD_ELEMENT__POLICY:
        return POLICY_EDEFAULT == null ? policy != null : !POLICY_EDEFAULT.equals(policy);
      case AiDslPackage.VM_FIELD_ELEMENT__TYPE:
        return type != null;
      case AiDslPackage.VM_FIELD_ELEMENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AiDslPackage.VM_FIELD_ELEMENT__DEFAULTVALUE:
        return defaultvalue != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (policy: ");
    result.append(policy);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //VMFieldElementImpl
