/**
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.aiDsl.impl;

import de.mindscan.ai.aidsl.aiDsl.AiDslPackage;
import de.mindscan.ai.aidsl.aiDsl.ELEMENTTYPE;
import de.mindscan.ai.aidsl.aiDsl.VMNodeOutElement;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>VM Node Out Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.impl.VMNodeOutElementImpl#getName <em>Name</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.impl.VMNodeOutElementImpl#getType <em>Type</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.impl.VMNodeOutElementImpl#isHasrequire <em>Hasrequire</em>}</li>
 *   <li>{@link de.mindscan.ai.aidsl.aiDsl.impl.VMNodeOutElementImpl#getInputreference <em>Inputreference</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VMNodeOutElementImpl extends MinimalEObjectImpl.Container implements VMNodeOutElement
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected ELEMENTTYPE type;

  /**
   * The default value of the '{@link #isHasrequire() <em>Hasrequire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHasrequire()
   * @generated
   * @ordered
   */
  protected static final boolean HASREQUIRE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isHasrequire() <em>Hasrequire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHasrequire()
   * @generated
   * @ordered
   */
  protected boolean hasrequire = HASREQUIRE_EDEFAULT;

  /**
   * The default value of the '{@link #getInputreference() <em>Inputreference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputreference()
   * @generated
   * @ordered
   */
  protected static final String INPUTREFERENCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInputreference() <em>Inputreference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputreference()
   * @generated
   * @ordered
   */
  protected String inputreference = INPUTREFERENCE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VMNodeOutElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AiDslPackage.Literals.VM_NODE_OUT_ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_NODE_OUT_ELEMENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ELEMENTTYPE getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(ELEMENTTYPE newType, NotificationChain msgs)
  {
    ELEMENTTYPE oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(ELEMENTTYPE newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isHasrequire()
  {
    return hasrequire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHasrequire(boolean newHasrequire)
  {
    boolean oldHasrequire = hasrequire;
    hasrequire = newHasrequire;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_NODE_OUT_ELEMENT__HASREQUIRE, oldHasrequire, hasrequire));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInputreference()
  {
    return inputreference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInputreference(String newInputreference)
  {
    String oldInputreference = inputreference;
    inputreference = newInputreference;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AiDslPackage.VM_NODE_OUT_ELEMENT__INPUTREFERENCE, oldInputreference, inputreference));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE:
        return basicSetType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_NODE_OUT_ELEMENT__NAME:
        return getName();
      case AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE:
        return getType();
      case AiDslPackage.VM_NODE_OUT_ELEMENT__HASREQUIRE:
        return isHasrequire();
      case AiDslPackage.VM_NODE_OUT_ELEMENT__INPUTREFERENCE:
        return getInputreference();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_NODE_OUT_ELEMENT__NAME:
        setName((String)newValue);
        return;
      case AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE:
        setType((ELEMENTTYPE)newValue);
        return;
      case AiDslPackage.VM_NODE_OUT_ELEMENT__HASREQUIRE:
        setHasrequire((Boolean)newValue);
        return;
      case AiDslPackage.VM_NODE_OUT_ELEMENT__INPUTREFERENCE:
        setInputreference((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_NODE_OUT_ELEMENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE:
        setType((ELEMENTTYPE)null);
        return;
      case AiDslPackage.VM_NODE_OUT_ELEMENT__HASREQUIRE:
        setHasrequire(HASREQUIRE_EDEFAULT);
        return;
      case AiDslPackage.VM_NODE_OUT_ELEMENT__INPUTREFERENCE:
        setInputreference(INPUTREFERENCE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AiDslPackage.VM_NODE_OUT_ELEMENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AiDslPackage.VM_NODE_OUT_ELEMENT__TYPE:
        return type != null;
      case AiDslPackage.VM_NODE_OUT_ELEMENT__HASREQUIRE:
        return hasrequire != HASREQUIRE_EDEFAULT;
      case AiDslPackage.VM_NODE_OUT_ELEMENT__INPUTREFERENCE:
        return INPUTREFERENCE_EDEFAULT == null ? inputreference != null : !INPUTREFERENCE_EDEFAULT.equals(inputreference);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", hasrequire: ");
    result.append(hasrequire);
    result.append(", inputreference: ");
    result.append(inputreference);
    result.append(')');
    return result.toString();
  }

} //VMNodeOutElementImpl
