/*
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.ide;


/**
 * Use this class to register ide components.
 */
public class AiDslIdeModule extends AbstractAiDslIdeModule {
}
