/*
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.mindscan.ai.aidsl.AiDslRuntimeModule;
import de.mindscan.ai.aidsl.AiDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AiDslIdeSetup extends AiDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AiDslRuntimeModule(), new AiDslIdeModule()));
	}
	
}
