/*
 * generated by Xtext 2.27.0
 */
package de.mindscan.ai.aidsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AiDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/mindscan/ai/aidsl/parser/antlr/internal/InternalAiDsl.tokens");
	}
}
